version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: query-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: querybuilder
    networks:
      - query-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: query-builder-app:1.6.1-SNAPSHOT
    container_name: query-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - query-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/querybuilder
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypassword

networks:
  query-network:
    driver: bridge

